---
title: "Read in field descriptions"
author: "Richard Gower"
date: "July 7, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## get the lookup data

Read in the description tables 

```{r dataPrep}
# read original file
library(xlsx)
wd <- getwd()  # gets the working directory
file <- paste(wd,"Data\\FieldDescriptions.xlsx", sep="/") # create path and file name

wb = loadWorkbook(file)
ws = getSheets(wb)
 
descriptionsTemp = data.frame(Table = as.character(),
                          FieldName=as.character(),
                          Type=character(),
                         Sample=character(),
                         Explanation=character(),
                         Values=character(),
                         Lookups=character(),
                         Comments=character(),
                         Missing=character(),
                         Actions=character())

for (sheetNum in (1:length(ws))){
  print(paste("Processing sheet:", names(ws)[sheetNum]))
  readSheet <- read.xlsx(file, sheetIndex=sheetNum, header=TRUE,stringsAsFactors=FALSE )

  print(readSheet)

  readSheet$Table = names(ws)[sheetNum] 

  descriptionsTemp = rbind(descriptionsTemp, readSheet)
  
}

fieldDescriptions.raw = descriptionsTemp[c('Table','FieldName','Type', 'Sample', 'Description', 'Values', 'Lookups','MissingValue', 'MissingCount', 'MissingPercent','SuspectData', 'Comments', 'Actions' )]
save(fieldDescriptions.raw, file='datafiles\\fieldDescriptions.raw.rda')

```
```{r}
#rm(lookups)
rm(descriptionsTemp)
rm(readSheet)
rm(wb)
rm(ws)
rm(file)
rm(sheetNum)
rm(wd)
```

