---
title: "Untitled"
author: "Wright, Aaron"
date: "July 17, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("caret")
library("ranger")
```

## R Markdown


```{r}
#load(paste(getwd(),"datafiles","accidents.rda",sep="/"))

#Use this chunk on final cleaned set to create train, test & holdout set
holdout.set=accidents[accidents$Date>='2015-01-01',]
non.holdout=accidents[accidents$Date<'2015-01-01',]

set.seed(123)
train = sample(1:nrow(non.holdout),nrow(non.holdout)*.1,rep=FALSE) #train on a 10% sample...due to size

train.data = non.holdout[train,]
test.data = non.holdout[-train,]
rm(non.holdout)
```





```{r}
train.sub <-subset(train.data, select=c("sev","Number_of_Vehicles", "Number_of_Casualties", "Speed_limit", "month", "day", "Wind", "Rain", "Snow", "Fog", "DryRd", "WetRd", "SnowRd", "IceRd", "FloodRd", "OilRd", "MudRd", "SiteIssue_Signal", "SiteIssue_Sign", "SiteIssue_Construction", "SiteIssue_PotHole", "SiteIssue_Mud", "SiteIssue_Oil", "Hazard_Animal", "Hazard_Ped", "Hazard_Object", "Hazard_PrevAcc", "UrbanRural", "vehMotoInd", "vehTramInd", "vehTowingInd", "vehTurningInd", "vehStoppedInd", "vehSkiddingInd", "vehLeavingInd", "vehFrontImpInd", "vehBackImpInd", "vehSideImpInd", "vehLeftDrInd"))
```



```{r}
row.has.na <- apply(train.sub, 1, function(x){any(is.na(x))})

predictors_has_NA <- train.sub[row.has.na,]
```



```{r}
# fit a random forest model (using ranger)
#rf_fit <- train(sev ~ ., data = train.sub, method = "ranger")

tgrid <- expand.grid(.mtry = 2:4, .splitrule = "gini", .min.node.size = c(10,20))

rf_fit <- train(sev ~., data = train.sub, method = "ranger", 
                trControl = trainControl(method="cv", number = 5, verboseIter = T, classProbs = T),
                tuneGrid = tgrid,
                num.trees = 100,
                importance = "permutation")

```

```{r}
varImp(rf_fit)
```


```{r}
rf_fit
```

```{r}
confusionMatrix(rf_fit)
```


```{r}
# fit a random forest model (using ranger)
#rf_fit <- train(sev ~ ., data = train.sub, method = "ranger")

tgrid2 <- expand.grid(.mtry = 2:4, .splitrule = "gini", .min.node.size = c(10,20))

rf_fit2 <- train(sev ~., data = train.sub, method = "ranger", 
                trControl = trainControl(method="cv", number = 5, verboseIter = T, classProbs = T, sampling = "up"),
                tuneGrid = tgrid2,
                num.trees = 100,
                importance = "permutation")

```


```{r}
varImp(rf_fit2)
```



```{r}
rf_fit2
```


```{r}
confusionMatrix(rf_fit2)
```



```{r}
# fit a random forest model (using ranger)
#rf_fit <- train(sev ~ ., data = train.sub, method = "ranger")

tgrid3 <- expand.grid(.mtry = 2:4, .splitrule = "gini", .min.node.size = c(10,20))

rf_fit3 <- train(sev ~., data = train.sub, method = "ranger", 
                trControl = trainControl(method="cv", number = 5, verboseIter = T, classProbs = T, sampling = "down"),
                tuneGrid = tgrid3,
                num.trees = 100,
                importance = "permutation")

```


```{r}
varImp(rf_fit3)
```



```{r}
rf_fit3
```


```{r}
confusionMatrix(rf_fit3)
```







```{r}
# fit a random forest model (using ranger)
#rf_fit <- train(sev ~ ., data = train.sub, method = "ranger")
library("MLmetrics")
tgrid4 <- expand.grid(.mtry = 2:4, .splitrule = "gini", .min.node.size = c(10,20))





rf_fit4 <- train(sev ~ ., data = train.sub, 
                            method = "multinom", 
                            trControl = trainControl(method = "cv", number = 5, returnResamp = "all",classProbs = TRUE, summaryFunction = multiClassSummary),
                            metric = "ROC", 
                            trace = FALSE)
```


```{r}
varImp(rf_fit4)
```



```{r}
rf_fit4
```


```{r}
confusionMatrix(rf_fit4)
```


```{r}
sensitivity(rf_fit4)

```



```{r}
# fit a random forest model (using ranger)
#rf_fit <- train(sev ~ ., data = train.sub, method = "ranger")
library("MLmetrics")

rf_fit5 <- train(sev ~ ., data = train.sub, 
                            method = "multinom", 
                            trControl = trainControl(method = "cv", number = 5, returnResamp = "all",classProbs = TRUE, 
                                                     summaryFunction = multiClassSummary, sampling = "up"),
                            metric = "ROC", 
                            trace = FALSE)
```


```{r}
varImp(rf_fit5)
```



```{r}
rf_fit5
```


```{r}
confusionMatrix(rf_fit5)
```









```{r}
models <- list(original_rf=rf_fit, over_rf=rf_fit2, under_rf=rf_fit3)

resampling <- resamples(models)
bwplot(resampling)
```
















```{r}
# predict the outcome on a test set
test_rf_pred <- predict(rf_fit, test.data)
# compare predicted outcome and true outcome
confusionMatrix(test_rf_pred, test.data$sev)
```











